// Shared filter operators and fields from dealFilterAddEditDialog
export const operators1 = [
  { value: "=", label: "= is" },
  { value: "!=", label: "≠ is not" },
  { value: "empty", label: "is empty" },
  { value: "not_empty", label: "is not empty" },
  { value: "<=", label: "≤ is less or equal to" },
  { value: "<", label: "< is less than" },
  { value: ">=", label: "≥ is more or equal to" },
  { value: ">", label: "> is more than" },
];

export const operators2 = [
  { value: "equals", label: "is" },
  { value: "notEquals", label: "is not" },
  { value: "isEmpty", label: "is empty" },
  { value: "isNotEmpty", label: "is not empty" },
  { value: "containsAny", label: "contains any of" },
  { value: "containsAll", label: "contains" },
  { value: "notContains", label: "does not contain" }
];

export const operators3 = [
  { value: "equals", label: "is" },
  { value: "notEquals", label: "is not" },
  { value: "isEmpty", label: "is empty" },
  { value: "isNotEmpty", label: "is not empty" },
  { value: "contains", label: "contains" },
  { value: "startsWith", label: "starts with" },
  { value: "notStartsWith", label: "does not start with" }
];

export const operators4 = [
  { value: "equals", label: "is" },
  { value: "notEquals", label: "is not" },
  { value: "isEmpty", label: "is empty" },
  { value: "isNotEmpty", label: "is not empty" },
  { value: "onOrBefore", label: "is exactly on or before" },
  { value: "before", label: "is before" },
  { value: "onOrAfter", label: "is exactly on or after" },
  { value: "after", label: "is after" }
];

export const fieldOptions = [
  { value: "activitiesToDo", label: "Activities to do" },
  { value: "acv", label: "ACV", isNumberType: true },
  { value: "apiCallsMade", label: "API Calls Made", isNumberType: true },
  { value: "appointmentStatus", label: "Appointment Status" },
  { value: "archiveTime", label: "Archive time", isDateType: true },
  { value: "arr", label: "ARR", isNumberType: true },
  { value: "assignedBdManager", label: "Assigned BD Manager" },
  { value: "attachedProduct", label: "Attached product" },
  { value: "blandDealIdentifier", label: "Bland Deal Identifier" },
  { value: "clientNumber", label: "Client Number" },
  { value: "clinic", label: "Clinic" },
  { value: "company", label: "Company" },
  { value: "consentCheckbox", label: "Consent Checkbox" },
  { value: "consultDate", label: "Consult Date", isDateType: true },
  { value: "contactPerson", label: "Contact person" },
  { value: "cosmeticProcedure", label: "Cosmetic Procedure" },
  { value: "creator", label: "Creator" },
  { value: "currencyOfACV", label: "Currency of ACV" },
  { value: "currencyOfARR", label: "Currency of ARR" },
  { value: "currencyOfMRR", label: "Currency of MRR" },
  { value: "currencyOfRevenue", label: "Currency of Revenue" },
  { value: "currencyOfValue", label: "Currency of Value" },
  { value: "currencyOfZandaInvoiceValue", label: "Currency of Zanda Invoice Value" },
  { value: "currentPracticeLocation", label: "Current Practice Location" },
  { value: "dateOfEnteringStage", label: "Date of entering stage", isDateType: true },
  { value: "dealClosedOn", label: "Deal closed on", isDateType: true },
  { value: "dealCreated", label: "Deal created", isDateType: true },
  { value: "dealStage", label: "Deal Stage" },
  { value: "doneActivities", label: "Done activities", isNumberType: true },
  { value: "electiveBreastSurgery", label: "Elective Breast Surgery" },
  { value: "electivaEntSurgery", label: "Electiva ENT Surgery" },
  { value: "electivaGastroenterology", label: "Electiva Gastroenterology" },
  { value: "electivaGeneralSurgery", label: "Electiva General Surgery" },
  { value: "electivaGynaecologyTreatments", label: "Electiva Gynaecology Treatments" },
  { value: "electivaNote", label: "Electiva Note" },
  { value: "electivaOrthopaedicTreatments", label: "Electiva Orthopaedic Treatments" },
  { value: "electivaTreatments", label: "Electiva Treatments" },
  { value: "electivaUrologyTreatments", label: "Electiva Urology Treatments" },
  { value: "electivaVisionTreatments", label: "Electiva Vision Treatments" },
  { value: "electivaLocations", label: "Electiva Locations" },
  { value: "enquiry", label: "Enquiry" },
  { value: "emailMessagesCount", label: "Email messages count", isNumberType: true },
  { value: "expectedCloseDate", label: "Expected close date", isDateType: true },
  { value: "gmcNumber", label: "GMC Number" },
  { value: "identiteLocation", label: "Identite Location" },
  { value: "identiteProcedure", label: "Identite Procedure" },
  { value: "label", label: "Label" },
  { value: "lastActivityDate", label: "Last activity date", isDateType: true },
  { value: "lastEmailReceived", label: "Last email received", isDateType: true },
  { value: "lastEmailSent", label: "Last email sent" },
  { value: "lastStageChange", label: "Last stage change" },
  { value: "location", label: "Location (City)" },
  { value: "lostReviewReason", label: "Lost Review Reason" },
  { value: "lostReason", label: "Lost Reason" },
  { value: "lostTime", label: "Lost time", isDateType: true },
  { value: "marketingContent", label: "Marketing Content" },
  { value: "marketingFBClid", label: "Marketing_FBClid" },
  { value: "marketingGClid", label: "Marketing_GCLID" },
  { value: "marketingMedium", label: "Marketing Medium" },
  { value: "marketingSource", label: "Marketing Source" },
  { value: "marketingTerm", label: "Marketing Term" },
  { value: "marketingConsent", label: "Marketing Consent" },
  { value: "medicalForm", label: "Medical_Form" },
  { value: "mrr", label: "MRR", isNumberType: true },
  { value: "nextActivityDate", label: "Next activity date", isDateType: true },
  { value: "nextSteps", label: "Next Steps" },
  { value: "operationDate", label: "Operation Date", isDateType: true },
  { value: "organization", label: "Organization" },
  { value: "owner", label: "Owner" },
  { value: "pipeline", label: "Pipeline" },
  { value: "pipelineType", label: "Pipeline Type" },
  { value: "probability", label: "Probability", isNumberType: true },
  { value: "referTelephoneNumber", label: "Does The Refer Telephone Number exists" },
  { value: "revenue", label: "Revenue", isNumberType: true },
  { value: "score", label: "Score", isNumberType: true },
  { value: "source", label: "Source" },
  { value: "sourceChannel", label: "Source channel" },
  { value: "stage", label: "Stage" },
  { value: "status", label: "Status" },
  { value: "submissionId", label: "Submission Id" },
  { value: "tcConsent", label: "TC Consent" },
  { value: "title", label: "Title" },
  { value: "totalActivities", label: "Total activities", isNumberType: true },
  { value: "treatment", label: "Treatment" },
  { value: "updateTime", label: "Update time", isDateType: true },
  { value: "value", label: "Value", isNumberType: true },
  { value: "wonTime", label: "Won time", isDateType: true },
  { value: "zandaInvoiceValue", label: "Zanda Invoice Value", isNumberType: true },
];

export const getOperatorsByField = (fieldValue: string) => {
  const fieldOperatorMap: { [key: string]: any[] } = {
    activitiesToDo: operators1,
    acv: operators1,
    apiCallsMade: operators2,
    appointmentStatus: operators3,
    archiveTime: operators4,
    arr: operators1,
    assignedBdManager: operators3,
    attachedProduct: operators2,
    blandDealIdentifier: operators3,
    clientNumber: operators1,
    clinic: operators2,
    company: operators3,
    consentCheckbox: operators2,
    consultDate: operators4,
    contactPerson: operators2,
    cosmeticProcedure: operators3,
    creator: operators2,
    currencyOfACV: operators2,
    currencyOfARR: operators2,
    currencyOfMRR: operators2,
    currencyOfRevenue: operators2,
    currencyOfValue: operators2,
    currencyOfZandaInvoiceValue: operators2,
    currentPracticeLocation: operators3,
    dateOfEnteringStage: operators4,
    dealClosedOn: operators4,
    dealCreated: operators4,
    dealStage: operators3,
    doneActivities: operators1,
    electiveBreastSurgery: operators2,
    electivaEntSurgery: operators2,
    electivaGastroenterology: operators2,
    electivaGeneralSurgery: operators2,
    electivaGynaecologyTreatments: operators2,
    electivaNote: operators2,
    electivaOrthopaedicTreatments: operators2,
    electivaTreatments: operators2,
    electivaUrologyTreatments: operators2,
    electivaVisionTreatments: operators2,
    electivaLocations: operators2,
    emailMessagesCount: operators1,
    expectedCloseDate: operators4,
    gmcNumber: operators3,
    label: operators2,
    lastActivityDate: operators4,
    lastEmailReceived: operators4,
    lastEmailSent: operators4,
    lastStageChange: operators4,
    location: operators2,
    lostReviewReason: operators2,
    lostReason: operators2,
    lostTime: operators4,
    marketingContent: operators2,
    marketingFBClid: operators2,
    marketingGClid: operators2,
    marketingMedium: operators2,
    marketingSource: operators2,
    marketingTerm: operators2,
    mrr: operators1,
    nextActivityDate: operators4,
    nextSteps: operators2,
    operationDate: operators4,
    owner: operators2,
    pipeline: operators2,
    pipelineType: operators2,
    probability: operators1,
    referTelephoneNumber: operators3,
    revenue: operators1,
    score: operators1,
    source: operators2,
    stage: operators2,
    status: operators2,
    submissionId: operators3,
    tcConsent: operators2,
    title: operators3,
    totalActivities: operators1,
    treatment: operators2,
    updateTime: operators4,
    value: operators1,
    wonTime: operators4,
    zandaInvoiceValue: operators1,
  };
  return fieldOperatorMap[fieldValue] || operators3;
};

export const dealStatusList = [
  { value: "1", label: "Open" },
  { value: "2", label: "Won" },
  { value: "3", label: "Lost" },
  { value: "4", label: "Closed" },
];
